### ISSUE TITLE
R.NET not working at all with R-3.5.0 pre-release

### ISSUE THREAD

**Issue by adpgithub** [jmp75/rdotnet#70]
Hi,
I found a strange issue. In my R dot Net application I am not able create R session when using R-3.5.0 pre-release version. It always worked with older versions of R (older than R-3.5.0). RStudio works with R-3.5.0 but not R dot Net. I am using R.NET 1.7.0. Older version R.NET 1.6.5 also failed for me.

I have attached a sample C#.NET project
Line number 26 in Program.cs throws exception. Here is line 26
`REngine engine = REngine.GetInstance();`

[RDotNetConsoleApp.zip](https://github.com/jmp75/rdotnet/files/1746722/RDotNetConsoleApp.zip)

You can download R pre-release from following link:
https://cran.r-project.org/bin/windows/base/rdevel.html

Please help.

**Comment by lrasmus** [comment]
I'm seeing the same.  It's throwing an exception trying to run this line:
https://github.com/jmp75/rdotnet/blob/master/R.NET/REngine.cs#L788

Which upstream is invoked from this call:
https://github.com/jmp75/rdotnet/blob/master/R.NET/REngine.cs#L359

It's getting back a 0 value for the pointer here:
https://github.com/jmp75/rdotnet/blob/master/R.NET/ExpressionVector.cs#L68-L69

I realize this doesn't offer any solution, but wanted to trace back for anyone else also looking at it.  I find it interesting we're seeing ongoing issues (of varying types) starting from 3.4.x and up.

**Comment by the-tourist-** [comment]
I have just upgrade R to version 3.5.0 and R.Net, no longer works.  I have problems every time I upgrade R, but this time I cannot work out how to get around it.  I am running Visual Studio 2013, because I rely on R.Net, and I haven't been able to get it to work on later versions.  I'm using R.Net 1.7.0 from nuget.  When I call REngine.GetInstance() I get the following error :
    A first chance exception of type 'System.NullReferenceException' occurred in RDotNet.dll
    Additional information: Object reference not set to an instance of an object

Irasmus, did you find a fix or work-around to the problem you mentioned with the pre-release 3.5.0.

**Comment by lrasmus** [comment]
Oh no!  Okay, I will admit that I was hoping this would kinda "fix itself" between pre-release and the official release, so I put it on the back burner.  Let me revisit now and see if I can identify what's going on, or at least some type of fix/workaround.  Thanks @the-tourist- for reporting it's still an issue!

**Comment by lrasmus** [comment]
Just read this at [https://cran.r-project.org/doc/manuals/r-release/R-ints.html#Rest-of-header](https://cran.r-project.org/doc/manuals/r-release/R-ints.html#Rest-of-header)

> Note that the size and structure of the header changed in R 3.5.0

So this means the sxpinfo header layout is different.  I'm going to see if I can get a version working locally that accounts for this.  If so, will have to figure out how to make this work for >=3.5 and <3.5 versions.

**Comment by lrasmus** [comment]
Made some progress.  I have a [work in progress commit](https://github.com/StatTag/rdotnet/commit/e2355ebd875e35189fb200a430eb5a58bd103300) where I believe I've aligned the structs to the R 3.5 changes.

The challenge I'm working on now is with vector coercion.  Per the [release notes](https://cran.r-project.org/doc/manuals/r-devel/NEWS.html):

> Coercing integer and numeric vectors to character also now uses the ALTREP framework to defer the actual conversion until first use.

I need to learn about the [ALTREP framework](https://svn.r-project.org/R/branches/ALTREP/ALTREP.html) now to understand how that works and how to get results out of my coerced vectors.

@jmp75 @the-tourist- @adpgithub - being optimistic that I'll sort that out, what is the preferred way to integrate this back into R.NET?  The project I'm using this in would ideally have a single R.NET included that figures out the right structs to use depending on the version of R running.  Is this a breaking enough change that 2 versions of R.NET ( R<3.5, R>=3.5) is more manageable?  Haven't thought this through yet, so suggestions are welcome.

**Comment by the-tourist-** [comment]
Hi Luke,

Thank you for this. I’m sorry you are are doing this on your own, I wish I could assist in some way. I know C# and R. But I don’t know how they are compiled, and are lost to offer you assistance.

**Comment by jmp75** [comment]
@lrasmus thank you for diagnosing this change. I had not picked up this thread until now - I need to check my notification/filters. Have you set up a fork I could set up as a remote? The usual github way forking/branching/pull request is usually the way to go but setting a fork is the most important step.

I have to find time (somehow) to assess whether we can maintain one package for all versions. Some structs were already varying across windows / linux already so in theory we could maintain backward compat pre/post 3.5 using a similar approach but this will likely be more substantial to work out how.

**Comment by lrasmus** [comment]
Hi @jmp75 - yes, we have a fork & branch for this change at: [https://github.com/StatTag/rdotnet/tree/r_3_5_0](https://github.com/StatTag/rdotnet/tree/r_3_5_0)
It's still "work in progress", but early feedback is welcome if you have the time.

Thanks for the note about the struct differences across windows and linux.  Once I get this working for R 3.5.0 I'll spend a little time also thinking about how this might be generalized, but yeah - I'm afraid it may be a lot more involved.

**Comment by dannyparsons** [comment]
Great that this is being worked on, thanks @lrasmus @jmp75 

I think I agree with @jmp75 that backward compatibility for pre 3.5 versions is desirable but not essential if it's going to be a lot of work. I think that's the most important part is rdotnet being compatible with the latest version(s) of R.

**Comment by Djanilton** [comment]
Hello @Irasmus, I replace only five files: CharacterVector.cs, Delegates.cs, SEXPREC.CS, sxpinfo.cs and VECTOR_SEXPREC.cs, is it correct? Because occurs the error "An unhandled exception of type "System.AccessViolationException" occurred in Unknown Module.
Attempt to read or write to protected memory. Usually, this is an indication that another memory is corrupted." at line 790 of REngine when executing the engine.initialize command.

**Comment by jmp75** [comment]
Thank you @lrasmus ; I have merged your branch into https://github.com/jmp75/rdotnet/tree/merge/StatTag . That branch also includes changes like moving to xunit and .netstandard2.0.  Most unit tests still pass with your changes; I'll diagnose a but more what fails to get a clearer picture.

**Comment by lrasmus** [comment]
@Djanilton and @jmp75 - I'm sorry I have had a busy week and haven't been able to sit down with this.  The branch wasn't completely fixed yet, but wanted to share progress as it was being made.

@jmp75 - IntegerVector failures are exactly the problem I left off on.  I think the big change is moving from DataPointer + offset to access vector data to using the VECTOR_ETL (or STRING_ETL for CharacterVectors).  I've been meaning to discuss that conceptually with you - I'm sure there's going to be some performance overhead, but by using those functions we abstract away the R implementation that handles checking for ALTREP structures.

Am planning to get back to this today.  I'll work from the branch you created - thanks for merging it with the other new features!

**Comment by jmp75** [comment]
@lrasmus I now see a bit more clearly where things are at with ALTREP, with your change and looking at R 3.5 source. Indeed that probably will make some of the fast operations assuming in memory continuity difficult.
I am curious as to how other interop packages to access R (from java, etc.) have dealt with this.

**Comment by jmp75** [comment]
@lrasmus I have used the test "RDotNet.S4ClassesTest.TestSlots" to tease out using the new Get_region methods. Seems to work out for integer and numeric vectors. Pushed to https://github.com/jmp75/rdotnet/tree/merge/StatTag  .  The new form of [Vector.ToArray](https://github.com/jmp75/rdotnet/blob/6444a36086d9d37c3aac6f6cefd4b4cf1c4c6e89/R.NET/Vector.cs#L85) is a proposal. Feel free to suggest another.

**Comment by zulu9r** [comment]
I'm so glad I read this!  I've been pulling my hair out for days over this.

I have an app that's been working fine with the "R" version that is installed with Microsoft's R Tools.

Then, I tested it on another PC with just the latest install of R (3.5) and no matter what I did, it wouldn't work.

So, I read this and installed 3.43 and it works again!

Please let us know when/if you are able to get it sorted @jmp75 and if any testing is needed.

Thanks for your work.

**Comment by lrasmus** [comment]
@jmp75 back to this, thanks for all the great changes!  I like the new form of Vector.ToArray that you've proposed - a nice, clean implementation, which would allow for the fast data access if ALTREP isn't being used.

**Comment by mortalrahu** [comment]
Hi, @lrasmus and @jmp75 

The same problem still exists, I installed 'RDotNet v1.7.0' using Nuget Package Manager, it throws the same NullPointerException.
Did you guys fix this already?

And I have tried to add references manually, but the DLL files were missing from the repository package.

Please let me know if there is a solution, I am in desperate need of the REngine.

Thank you

**Comment by the-tourist-** [comment]
I don’t think it has been fixed. I tried with a new installation of R 3.5 a few weeks ago and had the same problems, so reverted back to R 3.4.4

**Comment by mortalrahu** [comment]
@the-tourist- 
Thank you for the quick reply, great to know that R 3.4.4 is working, I would like to know how to integrate that with my project. I guess you are talking about the manual integration, right?
Please guide me through the process of integrating R 3.4.4 or provide me some resources

**Comment by the-tourist-** [comment]
Hi Rahul. 
I’m not associated with development of R.net in any way, I’m just an appreciative user.
I’m not sure what you mean by integrating.  I just installed the earlier version of R from 
https://cran.r-project.org/bin/windows/base/old/ . I’m happy enough to keep using this version until 3.5 is supported by R.net.

**Comment by kotzer3** [comment]
thats exaclty the way it works: 
uninstall 3.5.* and install latest 3.4 (3.4.4) from https://cran.r-project.org/bin/windows/base/old/. Then instanciating does work again. Thx goes to @ the-tourist-

**Comment by lrasmus** [comment]
@mortalrahu, @the-tourist-  - as far as I know this hasn't been officially merged in yet with support for R 3.5+.  We've been using the submitted code for several months now in our own project - so far so good - so if you're okay building locally vs. NUget, you can integrate it in.

**Comment by dannyparsons** [comment]
I'd really like to test this out on my own project as well. Is there some guide on how to build locally and incorporate in a project? Thanks.

**Comment by lrasmus** [comment]
@dannyparsons - are you using .NET Core?  One of the reasons we're using a forked repo is we haven't migrated, and need to keep some things separate in order to get it to compile.

**Comment by lrasmus** [comment]
I was able to get a build using the main repositories, but note when I did it it's tied to .NET 4.5.1, not Core.  Hopefully this will help @dannyparsons and @mortalrahu 

```
git clone https://github.com/jmp75/rdotnet.git
git clone https://github.com/jmp75/dynamic-interop-dll.git
cd rdotnet
git checkout merge/StatTag
cd ..
cd dynamic-interop-dll
git checkout tags/0.8.1
```
1. Create a new project in Visual Studio
2. Right click on Solution, Add -> Existing Project
3. Select dynamic-interop-dll/DynamicInterop/DynamicInterop.csproj
4. Right click on Solution, Add -> Existing Project
5. Select rdotnet/R.NET/RDotNet.csproj
6. Right click on Solution, Add -> Existing Project
7. Select rdotnet/RDotNet.NativeLibrary/RDotNet.NativeLibrary.csproj
8. In your project, add References from the solution for DynamicInterop, RDotNet and RDotNet.NativeLibrary

NOTE: In the RDotNet and RDotNet.NativeLibrary projects, you may need to re-add the DynamicInterop reference, and may need to change .NET versions for the projects so they match.

**Comment by ChechyLevas** [comment]
Does anyone have any idea of when this will be fixed in the Nuget version? (for all those involved, your efforts are massively appreciated!)

**Comment by gpriaulx** [comment]
I appear to be having the same issue with both the current R version and an older version that others have reported working. I have taken the ['hello world' example](http://jmp75.github.io/rdotnet/tut_basic_types/) form the documentation, and tried to execute it in an isolated project under .Net 4.7.

On `REngine engine = REngine.GetInstance();` I am getting a `NullReferenceException` which appears to be internal. It looks like this is known and discussed in a few other places, but I haven't found any conclusive resolution that has worked for me. Is this still an issue?

I have tried both R versions 3.4.3, and 3.5.1, and  following the advice [in this Stack Overflow question](https://stackoverflow.com/questions/49983252/how-to-solve-rdotnet-rengine-nullreference-exception), both resulting in same outcome. 

Any update on this, or anything I do to assist in reaching a resolution.

**Comment by lrasmus** [comment]
@jmp75 anything we can do to help finalize merging the R 3.5+ code into the master branch (sorry, know you're busy)

**Comment by Ductomaniac** [comment]
@lrasmus any chance you can provide the built package? I tried following your instructions but am still running into NullReference Exceptions when building on R 3.5.1

**Comment by lrasmus** [comment]
@Ductomaniac - sorry for the slow reply.  Let me know if you're able to build directly from https://github.com/StatTag/rdotnet, otherwise I can provide (unofficial, unsupported) binaries.

**Comment by MarkFleet** [comment]
@lrasmus - Do you know of any other differences with this version?

As an example, using R.Net with 3.3.3 I was simply able to run the below to get a list of all objects in R.
`List<string> symbols = engine.Evaluate("ls()").AsCharacter().ToList();`
This will still run without error but the list contains zeros only.

I appear to also be having an issue with ICharacterDevice but I need to do more investigation to be sure.

**Comment by Biopticon** [comment]
Hello,

So what is the current state of affairs of R.Net with the current versions of R>=3.5.x? The explanation for the layman, please. Can we run any R project with R 3.5 and above using the current off the shelf R.Net without doing this or that? Otherwise, R.Net is not working for the future R releases.

**Comment by lrasmus** [comment]
@Biopticon - this isn't an official response, but my understanding is the layman response is "R.NET does not work with R 3.5 and higher".  Am hoping @jmp75 will be able to provide an update soon if the branch with the fix looks good enough to merge in.

@MarkFleet - sorry for the late reply, I didn't explicitly test but that behavior sounds like it's related to the ALTREP changes.  Curious about your ICharacterDevice issue, and if you're still seeing it.

**Comment by MarkFleet** [comment]
@lrasmus - Thanks for coming back to me. Regarding the ALTREP changes, does that mean there is an issue or do I now need to do something different so get the results from "ls()" into a list?

Yes there is definitely something not right with ICharacterDevice. I implement my own ICharacterDevice so I can use a basic console within my application. If I run a simple R command such as "version" then the first time works perfect and the results are written to my console. If I then run the same command or anything else, nothing happens - WriteConsole() isn't triggered at all. No exceptions are thrown and the other code continues to run. Strangely however I do get a ding as if there is a problem somewhere! If I switch to R 3.3.3 then it works flawlessly every time.

Edit: Just doing some more tests and if I run "R.Version()" instead of "version" then this will work over and over again correctly triggering WriteConsole(). As soon as I run "version" once, it will stop working. It is not however specific to "version". If I type "mtcars" as an example then the same will happen. Odd!

Any ideas?

**Comment by lrasmus** [comment]
@MarkFleet regarding ALTREP, there are issues and I don't believe there are workarounds with the current main R.NET branch for the issue.  I don't want to drive folks away from the main repo, but we have a fork with support for R 3.5+ built in (https://github.com/StatTag/rdotnet).

That is very odd behavior with the ICharacterDevice.  I'm not aware of anything version-specific within R that would have caused this, but I'm still inclined to think it could be related to the ALTREP changes.  If you have time to try our fork, I'm curious if it works for you or not.

**Comment by MarkFleet** [comment]
@lrasmus - Thanks again for the quick reply + tenaciously keeping the momentum going in this thread.

I am actually using that fork which is why I was surprised that this did not work.

**Comment by lrasmus** [comment]
Oh snap!  Apparently I can't read... yeah you clearly stated you're using our branch.  In that case I need to do some testing!  Will get back to you today.

**Comment by lrasmus** [comment]
@MarkFleet - I was able to reproduce on my end.  I'm curious if your project Build options has "Prefer 32-bit" enabled or not?  What I discovered is that when this is on, it's throwing off the memory calculations.  I obviously need to properly fix this, but curious if you have that setting on and if disabling it appears to address the problem?

**Comment by lrasmus** [comment]
@MarkFleet - thanks for the update on platform, and confirmation it is working for you on a 64-bit platform.  I'm going to work on it this week, need to set up a 32-bit development environment where I can run tests, etc.

**Comment by MarkFleet** [comment]
@lrasmus - Excellent. Thanks!

**Comment by adpgithub** [comment]
@Irasmas: I tried cloning the 'StatTag' branch using your steps above (thank you for the steps). After compiling I used the R.NET DLLs in my project, I was able to create an R instance, but as soon as I tried running simple statements like "a =10" I did not see any output. Appears like instance is unstable. Basically, after instance creation command execution did not work. I just wanted to report it.
Is there any other branch which is working with R 3.5.x? 
Thanks.

**Comment by lrasmus** [comment]
Agh, alright @adpgithub sorry to you as well.  I really thought I had this up an running.  It sounds like you built the DLLs from R.NET, then imported the DLLs into another project for use?  In the project we're using this in, we have all of the R.NET projects included so it's built together.  Shouldn't make a difference, but wanted to clarify.

**Comment by lrasmus** [comment]
@adpgithub and @MarkFleet - whenever you have a chance, would love to know if [https://github.com/StatTag/rdotnet/tree/altrep_32bit_fix](https://github.com/StatTag/rdotnet/tree/altrep_32bit_fix) works for you now.

**Comment by MarkFleet** [comment]
@lrasmus - Sure. I will give this a go today and come back to you shortly.

**Comment by MarkFleet** [comment]
@lrasmus - I have done some testing and there still appears to be issues unfortunately. I am using my very simple example again: `List<string> symbols = engine.Evaluate("ls()").AsCharacter().ToList();`

If prior to running this I run:
`x <- 1`
`testinglongname <- 2`

The string list named symbols contains:

> 0
> ongname

When I had previously tried this on 32-bit, I had only used short names which is why everything was 0. I hope that helps but let me know if you need me to test anything else specific.

**Comment by lrasmus** [comment]
@MarkFleet - got e-mail notification with your reply, but for some reason am not seeing it here (yet?).  Thanks for testing so quickly.  I was able to get this to produce the expected results (https://github.com/lrasmus/RDotNetTestApp/tree/MarkFleet) and was wondering if this simplified test application works or not for you?  I tried it with explicit x86, x64, and Any CPU with "Prefer 32-bit" both enabled and disabled.  If this test app works but the code still fails in your other VSTO, I'll create a VSTO project for testing to see what's going on.

**Comment by lrasmus** [comment]
That's awesome to hear @MarkFleet, thanks for the update!  I'll take a look at output / ICharacterDevice next.

**Comment by lrasmus** [comment]
Here's what I was able to find.  When R.NET evaluates an expression, it checks to see if the AutoPrint flag is set, if the result is valid, and if R's set to show results (https://github.com/stattag/rdotnet/blob/master/R.NET/REngine.cs#L930-L933).

The last check to R.NET's GetVisible() (https://github.com/stattag/rdotnet/blob/master/R.NET/REngine.cs#L961) is returning false once I run:
engine.Evaluate("version");

If I take out the call to evaluate the version command, the other commands will print to my custom device.

I'm not convinced this is expected behavior, but may need to look at some of the R internals to better understand it.  @MarkFleet - in your earlier report, you had noted this appear with multiple calls to "version".  Is this the main scenario that you're seeing this in, or are there other examples?

**Comment by MarkFleet** [comment]
@lrasmus - Interesting. Yes I cannot imagine that this is the expected behavior. The issue is definitely not specific to "version". Try also viewing the built-in dataframe "mtcars" which will do the same thing.

I noticed that if you run "a <- mtcars" it actually prints "mtcars" at the same time. "a" should simply now be a copy of "mtcars" and nothing would previously have been printed at this point. Sounds like this is connected with the AutoPrint flag / GetVisible() ?

**Comment by MarkFleet** [comment]
@lrasmus - I also noticed that this version appears to be slower. I observed this when creating large dataframes (from Excel ranges). I do this in a few steps: creating an object array from the Excel range, creating a vector (with CreateNumericalVector() for example) per column and then joining all the vectors back together again at the end into a single dataframe. I will do some further testing to work out exactly which bit is slower now.

**Comment by MarkFleet** [comment]
@lrasmus - I have done some further speed tests and the good news is that it doesn't appear to be the creation of vectors itself which is slower. It is simply engine.ForceGarbageCollection() which is slower for me.

As I mentioned briefly, I am creating many vectors of different data types in quick succession before joining them together as a dataframe. In the past, I experienced very occasional memory issues when doing this and adding ForceGarbageCollection() after each iteration resolved this although I know this shouldn't really be required. ForceGarbageCollection() used to be almost instant but it now takes around 60ms which soon adds up when I am doing this over and over. It takes almost as long if I run ForceGarbageCollection() immediately again.

Any idea why this would be slower now? I am going to see if I can get away with removing this line altogether from my code but just I case I can't.

Many thanks!

**Comment by lrasmus** [comment]
@MarkFleet - thanks for the updates and continued testing!  Regarding the CharacterDevice output, what's interesting is that I'm seeing consistent behavior between R 3.4.3 and R 3.5.2.  I tried out "a <- mtcars" and as you saw it's dumping out mtcars to the console.  That weird issues with "version" also appears.  So not anything related to R 3.5+ from what I can see.  I'll revisit with older versions of R.NET to see if there's a difference.  It sounded like this problem started appearing for you with my branch of R.NET, but wasn't behavior you saw before correct?

For the slowness - it looks like engine.ForceGarbageCollection() is just calling R_gc.  I'm wondering if we can create an R script that mimics this behavior and see if GC is just slower across versions of R.  If not, then we can investigate how R.NET is allocating objects to see what's going on there.

**Comment by lrasmus** [comment]
@MarkFleet - I'm not sure if this reflects what you're doing, but [in this gist](https://gist.github.com/lrasmus/13131f58c46345f167ac6b6035e5af7c) I tested explicit GC calls in R directly, and there is a slowdown in R 3.5* compared to R 3.4*.  I think this is internal to R, and not anything specific with R.NET.  Let me know if you disagree.

**Comment by MarkFleet** [comment]
@lrasmus - Apologies for the delay in coming back to you.

Regarding GC, I had not realised that this was simply calling R's internal GC function. I have also done some testing and agree that it is R itself where the slowdown occurs. Annoying that its slower but glad nothing to do with R.NET.

That surprises me about R 3.4.3 doing the same with regards to the CharacterDevice. Our organisation isn't very fast to upgrade R versions so we are actually still on R 3.3.3 where these issues do not occur. I effectively expected the CharacterDevice to dump out the same stuff as R's own RGui. If I open the RGui for 3.5.1 and run "a <- mtcars" then mtcars is not output. There is also no issue running "version" multiple times in the RGui. I can confirm that the unexpected behavior occurs with the 1.7.0 NuGet version of R.NET and R 3.4.3. Although not related to this branch, do you agree that this appears to be an existing bug?

**Comment by lrasmus** [comment]
No apologies needed @MarkFleet - I may be a little delayed in replies here myself.

An update on the character device side.  I narrowed it down that the behavior changed starting in R 3.4.2.  I _think_ it's related to this commit: https://github.com/wch/r-source/commit/36f21ed31db7863c6db52a070d451a2296e8a2b4#diff-981639ef19814ebf596038653cb5f3af   I want to now see why the RGui behaves as we would expect it to.  We may need to adjust R.NET accordingly if there is different handling about when/how to display results.

**Comment by lrasmus** [comment]
@MarkFleet and others - my apologies once again.  Nothing like a public internet record showing I'm a bad developer :P  I found an issue with 32-bit version and accessing vector structures and strings.  The following code will reproduce the error:
```
using RDotNet;
using System;
using System.Linq;

namespace RDotNetTestApp
{
    class Program
    {
        static void Main(string[] args)
        {
            REngine.SetEnvironmentVariables();
            var device = new ExtendedCharacterDevice();
            using (var engine = REngine.GetInstance(null, true, null, device))
            {
                var response = engine.Evaluate("summary(cars)");
                var attributeName = response.GetAttributeNames().FirstOrDefault(x => x.Equals("dimnames", StringComparison.InvariantCultureIgnoreCase));
                var dimnames = response.GetAttribute(attributeName).AsList();
                foreach (var dimname in dimnames)
                {
                    Console.WriteLine("  {0}", string.Join(", ", dimname.AsCharacter()));
                }
            }
        }
    }
}
```

I just pushed up a fix for this.  Briefly, it has to deal with how C# aligns structs when bridging from C/C++, and also with me not having changed the legacy approach to access data (hint: use R's DATAPTR function instead of calculating memory offsets directly).

**Comment by lrasmus** [comment]
Thanks @MarkFleet !!  Right now it's updated at https://github.com/StatTag/rdotnet/tree/altrep_32bit_fix

**Comment by Biopticon** [comment]
Hello Luke and Mark,

 

                Does this mean that now R.NET is working properly under R 3.5.x? If so how to we get the new version?

 

                Thank you very much for your efforts to fix this problem.

 

Cem

**Comment by gusicadnan** [comment]
Hello people,

Yeah, I have the same question.  
Is there a way to get R.NET working properly under R 3.5.x? And how to do it?
Thanks in advance and we appreciate your effort to solve this problem!

Best regards,

**Comment by MarkFleet** [comment]
Hi @lrasmus ,

So just checking, should this resolve the issue I was seeing with the character device i.e. "version" and "mtcars"? If so then this doesn't appear to act any differently when using https://github.com/StatTag/rdotnet/tree/altrep_32bit_fix

Mark

**Comment by lrasmus** [comment]
Oh gosh, sorry @MarkFleet - this was unrelated to the character device issue!  I should have stated that.  This was purely around support for R 3.5.  I knew you had tried out the branch before, and wanted you to know I had discovered an issue on 32-bit platform (and that if you were using it, would likely be affected)

**Comment by Biopticon** [comment]
This project has many sites and ways. This is very confusing to many of us who just want to use this great tool to be able to access R libraries from C#, that’s all. I suggest you, the developers please unify all these sites under one, and choose one kind of update path, and one progressing version. How about version 1.8, but not your version or his/her version on this site or that site. We are very grateful that you are doing incredible job to get this tool to work under current R libraries.  Let’s make its use simple and effective. Thank you all.
    	
    	

    	Cem Girit
    
  




On Mon, Jan 28, 2019 at 10:25 PM -0500, "Luke R." <notifications@github.com> wrote:












@Biopticon, @gusicadnan - what is your preferred way to access R.NET releases (code vs. NuGet)?  I'll be folding that branch into our master branch at a different repository.  I don't want to drive people there away from what @jmp75 has been maintaining, but unfortunately I don't have rights on this repo or in NuGet to release.  Am hoping @jmp75 may have a chance to chime in on incorporating the changes for R 3.5 here, or what the best path forward is to help maintain this project.

**Comment by MarkFleet** [comment]
@lrasmus - No problem at all! I thought that may have been the case due to the mention of 32-bit. Just to confirm that I was able to reproduce the error when running your code in the old version. The latest version corrected this. I also used this version within some of my more complex tools and noted no other problems.

**Comment by lrasmus** [comment]
Thanks @Biopticon, point taken!  Will try to coordinate with @jmp75 the best path forward for a consolidated source.

Thanks @MarkFleet for testing!  Regarding the character device issues, I've continued looking into that but haven't come up with anything yet (sorry).  Haven't given up yet though.

**Comment by Biopticon** [comment]
Hello @jmp75 and @markfleet,

 

                Thank you so very much. We are grateful for this very volunteered work. We are looking forward for a solution that will be useful to many users like us. 

 

                Sincerely,

Cem

**Comment by MarkFleet** [comment]
Hi @lrasmus ,

Just checking in to see if there happened to be any more progress on this?

Many thanks!

Mark

**Comment by lrasmus** [comment]
Thanks @MarkFleet, I had followed up with @jmp75 via e-mail listed on his GitHub page but have not received anything back.  Open to suggestions from the community on how they'd like to see this move forward.

**Comment by UnclAlDeveloper** [comment]
I'd like to thank those who worked on the stattag version.  I just tried downloading it onto my computer and R.net seems to be working fine with R 3.5.3.

**Comment by MarkFleet** [comment]
Hi @lrasmus, just to confirm that I also tried to contract @jmp75 without any luck. In an ideal world I would like to see @jmp75 transfer ownership to yourself if he no longer has time for this project. Really hoping that we can get a 1.8.0 into nuget!

**Comment by UnclAlDeveloper** [comment]
@Irasmus, are you able to look at rClr?  I just had to revert to R-3.4.4 again because rClr doesn't work with R-3.5 and @jmp75 mentioned that it was related to the same issue as with rdotnet.

**Comment by Biopticon** [comment]
Hello All,

 

                Is this true, that now R.NET works under R3.5.3? IS this official? Can we download the latest version and  from where? Thank you for all of you.

 

                Sincerely,

Cem

**Comment by jmp75** [comment]
There is a pre-release [R.NET nuget package](https://www.nuget.org/packages/R.NET/) for user testing. Related and since @UnclAlDeveloper mentioned it rClr appears to be working really rather well on R 3.5, currently on a testing branch. 

Unit tests are still a watchpoint at this stage (not always repeatable behavior), though perhaps not indicative of major problems for "real" use, hence the prerelease.

Shortly, thank you to people in this thread; will follow up with proper due credits for contributions.

**Comment by jmp75** [comment]
[R.NET 1.8.1](https://www.nuget.org/packages/R.NET/1.8.1) is up on nuget, after a month of pre-release and some limited but positive feedback.

Short release notes is: Migration to .NET Standard 2.0, support for R 3.5.x, and moving to an MIT license. The license includes copyright attribution to the contributors.

**Comment by dannyparsons** [comment]
Thank you very much to everyone for the updated version.

In using R.NET 1.8.1 I have found an issue with getting values from character columns in a data frame. When I have a data frame with a character column, if I used `.AsDataFrame` to get a `DataFrame` object the character columns always contain empty values (`""`). Factor columns seem to work fine and accessing a character column directly with `.AsCharacter` also works fine. Below is an example. This was consistent for R 3.5.0, 3.5.3 and 3.6.0. In R 3.4.4 this works correctly. Could this be related to previous issues with character device?

```
        Dim engine As REngine
        Dim expression As SymbolicExpression

        REngine.SetEnvironmentVariables()
        engine = REngine.GetInstance()
        engine.Initialize()

        engine.Evaluate("x <- data.frame(c1 = c('a', 'b'), stringsAsFactors = FALSE)")
        expression = engine.GetSymbol("x")

        Console.WriteLine("Values as characters:")
        Console.WriteLine(expression.AsDataFrame(0)(0))
        Console.WriteLine(expression.AsDataFrame(0)(1))
        Console.WriteLine("*********************")

        engine.Evaluate("y <- data.frame(x = c('a', 'b'), stringsAsFactors = TRUE)")
        expression = engine.GetSymbol("y")

        Console.WriteLine("Values as factor:")
        Console.WriteLine(expression.AsDataFrame(0)(0))
        Console.WriteLine(expression.AsDataFrame(0)(1))
        Console.WriteLine("*********************")

        engine.Evaluate("c1 <- x$c1")
        expression = engine.GetSymbol("c1")

        Console.WriteLine("Values direct from column:")
        Console.WriteLine(expression.AsCharacter(0))
        Console.WriteLine(expression.AsCharacter(0))
        Console.WriteLine("*********************")
```
With output:
```
Values as characters:
'R.Net-Test.exe' (CLR v4.0.30319: R.Net-Test.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.


*********************
Values as factor:
a
b
*********************
Values direct from column:
a
a
*********************

```

**Comment by MarkFleet** [comment]
All,

Just to confirm that I am still having issues with the character device in this version. I knew this would be the case to an extent but this appears to be doing less than the @lrasmus 's non Nuget version? Previously, running "mtcars" would run WriteConsole() in the CharacterDevice correctly the first time but then WriteConsole() would not run if "mtcars" (or anything else) was ran again. WriteConsole() no longer appears to be ran for me at all. Only errors are triggering WriteConsole(). This is on all versions of R. I have only tried 32-bit so far (within Microsoft Excel).

This does stop me using the new version as I use this within an application which has a console to replicate the standard RGui.

It doesn't sound like @dannyparsons issue is related?

Kind regards

Mark

**Comment by jmp75** [comment]
@MarkFleet one change with 1.8.1 is the default value of REngine.AutoPrint. This had been set to `true` by a contributor in the past to try to match the R console output as closey as possible, but for larg-ish data this has too much of a performance impact so I reverted to `false`.  Have a look at https://github.com/jmp75/rdotnet-support/commit/ea7f0a3d38f326c2f9810558d2e673efea60c2ad to elicit observed and desired behavior  and could you enter a separate issue / feature request?  I do observe something of a difference between first expression evaluation and subsequent ones, if I get what you describe correctly.

**Comment by MarkFleet** [comment]
@jmp75 I was not aware of REngine.AutoPrint. Thanks for the demo code. That seems a good idea to set this to false by default and I will override to true when getting an instance of the engine. My first expression evaluation is now printing correctly with subsequent evaluations not - @lrasmus previously narrowed down to being an issue since R 3.4.2. I will raise this as a separate issue.

**Comment by adpgithub** [comment]
Hi,
I tested version 1.8.2 and it works as expected. Thank you so much everyone for putting so much effort to make it work. Cheers
